In [17]:
import numpy as np
np.random.seed(0)  # seed for reproducibility valore massimo escluso 


In [2]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
x4 = np.random.randint(20, size=(2,5,6,8))

In [18]:
print("x2 ndim: ", x2.ndim) #il numero di dimensioni

x2 ndim:  2


In [4]:
print("x4 size",x4.size) #la dimensione totale dell'arrey

x4 size 480


In [5]:
print("x3 shape",x3.shape) #la dimensione di ogni dimensione 

x3 shape (3, 4, 5)


In [21]:
x1 #partono sempre da 0 gli indici 

array([5, 0, 3, 3, 7, 9])

In [15]:
x2[2,0] #tra parentesi indice di posizione 

1

In [22]:
print("dtype",x4.dtype)#tipo di matrice 


dtype int32


In [24]:
x1[-1]

9

In [38]:
x2[0,0]= 1 #dare un valore specifico a un indice sovrascrivendo quello precedente 
x2

array([[1, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [29]:
#slincing creare sottomatrici 
x=np.arange(10)

In [30]:
x[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [34]:
x[0:10:2] #dato partenza dato finale passo/avanzamento

array([0, 2, 4, 6, 8])

In [36]:
x5=np.arange(50)
#si può definire anche solo un elemento
x5[::5] #solo passo 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [48]:
x5[::-7] #in ordine descrescente 

array([49, 42, 35, 28, 21, 14,  7,  0])

In [39]:
x2


array([[1, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [49]:
x2[:2, :3] #due righe e tre colonne 

array([[1, 5, 2],
       [7, 6, 8]])

In [59]:
x10= np.random.randint(10, size=(10,10))

In [65]:
x10[4:6:,0:10:] #da tabella 10x10 prende ogni due di riga e di colonna 

array([[7, 9, 6, 0, 8, 8, 2, 8, 4, 8],
       [6, 2, 0, 5, 2, 7, 5, 4, 3, 1]])

In [75]:
x10

array([[8, 4, 3, 4, 4, 9, 3, 5, 5, 1],
       [4, 6, 3, 4, 7, 5, 9, 9, 7, 0],
       [8, 6, 9, 9, 3, 3, 8, 9, 2, 3],
       [4, 2, 6, 0, 4, 1, 3, 0, 6, 2],
       [7, 9, 6, 0, 8, 8, 2, 8, 4, 8],
       [6, 2, 0, 5, 2, 7, 5, 4, 3, 1],
       [3, 2, 7, 7, 1, 0, 0, 7, 2, 0],
       [5, 2, 9, 8, 7, 7, 6, 2, 1, 9],
       [8, 4, 7, 4, 8, 2, 6, 8, 1, 9],
       [1, 8, 1, 0, 2, 9, 7, 5, 0, 2]])

In [68]:
print(x10[0]) #scrittura compatta 

[8 4 3 4 4 9 3 5 5 1]


In [113]:
x2

array([[1, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [119]:
x2_sub_copy = x2[:2, :2].copy()
#se aggiunto .copy non modifica la matrice origianle 
print(x2_sub_copy)

[[1 5]
 [7 6]]


In [117]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [118]:
x2

array([[1, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [126]:
grid = np.arange(1, 17).reshape((4, 4)) 
#cambia le dimesioni da mono a quadridimensionale 
print(grid)
#non serve più di tanto 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [127]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])
#concatena le matrici 

array([1, 2, 3, 3, 2, 1])

In [130]:
z= 99,99,99 #può esser fatto per riga ma anche per collonna
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [133]:
grid = np.array([[1, 2, 3],       #per colonna 
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [135]:
#nel caso hanno dimensioni diverse 
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],     
                 [6, 5, 4]])
np.vstack([x, grid])          
#np.vstack specifica che vengono orientate per colonne 

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [136]:
y = np.array([[99],
              [99]])
np.hstack([grid, y]) 
#np.hstack per righe 

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [137]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)
#separa in matrici differeti e indica su quali indici tagl

[1 2 3] [99 99] [3 2 1]
